# Generated by Django 4.1.3 on 2022-12-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_apointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('contact', models.BigIntegerField()),
                ('a_date', models.DateTimeField()),
                ('department', models.CharField(max_length=20)),
                ('d_name', models.CharField(max_length=20)),
            ],
        ),
    ]
